apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metrics-app.secretName" . }}
  labels:
    {{- include "metrics-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  PASSWORD: {{ .Values.secret.password | quote }}
